=== xiaomutou/myshop/WebRoot/xml/product.dtd
<!ELEMENT products (type*,product*)>
<!ELEMENT product (pname,price)>
<!ELEMENT pname (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT type (tname)>
<!ELEMENT tname (#PCDATA)>

<!ATTLIST product
	id ID #REQUIRED
	name CDATA #IMPLIED
	type IDREFS #REQUIRED
	tname NMTOKEN #IMPLIED
	note (good|bad|verygood|verybad) "good"
>
<!ATTLIST type 
	id ID #REQUIRED
	name CDATA #REQUIRED
>

=== xiaomutou/myshop/WebRoot/xml/product.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE products SYSTEM "product.dtd">
<products>
	<type id="C" name="diannao">
		<tname>电脑</tname>
	</type>
	<type id="C2" name="dinano_mini">
		<tname>电脑mini</tname>
	</type>
	<product type="C C2" id="P1" tname="dinannao2" note="good">
		<pname>电脑</pname>
		<price>1999</price>
	</product>
</products>
