=== xiaomutou/myshop/WebRoot/xml/student.dtd
<!ELEMENT student (id,name,age,empty,any,pcdata,brother+,sister*)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT empty EMPTY>
<!ELEMENT any ANY>
<!ELEMENT pcdata (#PCDATA)>
<!ELEMENT brother (#PCDATA)>
<!ELEMENT sister (#PCDATA)>

=== xiaomutou/myshop/WebRoot/xml/demo.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--  <!DOCTYPE student [
	<!ELEMENT student (name,age)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT age (#PCDATA)>
]>-->
<!DOCTYPE student SYSTEM "student.dtd">
<student>
	<id></id>
	<name></name>
	<age></age>
	<empty/>
	<any></any>
	<pcdata></pcdata>
	<brother></brother>
	<brother></brother>
	<sister></sister>
</student>
