=== xiaomutou/myshop/WebRoot/xmlschema/person.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="localhost" xmlns:my="localhost" elementFormDefault="qualified">
	<xs:element name="person">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="fullname">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="firstname" type="xs:string"/>
							<xs:element name="lastname" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="gender">
					<xs:complexType>
						<xs:choice minOccurs="0" maxOccurs="5">
							<xs:element name="male" type="xs:string"/>
							<xs:element name="female" type="xs:string"/>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="course">
					<xs:complexType>
						<xs:all minOccurs="0" maxOccurs="1">
							<xs:element name="java" type="xs:string"/>
							<xs:element name="XML" type="xs:string"/>
							<xs:element name="JavaScript" type="xs:string" maxOccurs="1"/>
						</xs:all>
					</xs:complexType>
				</xs:element>
				<xs:element name="letter">
					<xs:complexType>
						<xs:sequence>
							<xs:group ref="my:myGroup"/>
							<xs:element name="c" type="xs:string"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="content">
					<xs:complexType>
						<xs:attributeGroup ref="my:myattrGroup"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="ws">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:whiteSpace value="replace"></xs:whiteSpace>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="date">
					<xs:simpleType>
						<xs:list itemType="xs:date"></xs:list>
					</xs:simpleType>
				</xs:element>
				<xs:element name="union">
					<xs:simpleType>
						<xs:union memberTypes="my:sizeInt my:sizeStr"></xs:union>
					</xs:simpleType>
				</xs:element>
				<xs:element name="complex">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:int">
								<xs:attribute name="id" type="xs:short"></xs:attribute>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="choice">
					<xs:complexType>
						<xs:choice maxOccurs="20">
							<xs:element ref="my:hw"/>
						</xs:choice>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
<xs:simpleType name="sizeInt">
	<xs:restriction base="xs:integer">
		<xs:enumeration value="10"/>
		<xs:enumeration value="20"/>
		<xs:enumeration value="30"/>
	</xs:restriction>
</xs:simpleType>
<xs:simpleType name="sizeStr">
	<xs:restriction base="xs:string">
		<xs:enumeration value="small"/>
		<xs:enumeration value="middle"/>
		<xs:enumeration value="big"/>
	</xs:restriction>
</xs:simpleType>

<xs:complexType name="complex">
	<xs:sequence>
		<xs:element name="hello" type="xs:string"></xs:element>
	</xs:sequence>
</xs:complexType>

	<xs:group name="myGroup">
		<xs:sequence>
			<xs:element name="a" type="xs:string"/>
			<xs:element name="b" type="xs:string"/>
		</xs:sequence>
	</xs:group>
	<xs:attributeGroup name="myattrGroup">
		<xs:attribute name="id" type="xs:string"/>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="comment" type="xs:string"/>
	</xs:attributeGroup>
	
	<xs:element name="hw" type="xs:string"/>


</xs:schema>

=== xiaomutou/myshop/WebRoot/xmlschema/person.xml
<?xml version="1.0" encoding="UTF-8" ?>
<person xmlns="localhost" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="localhost person.xsd">

	<fullname>
		<firstname>hello</firstname>
		<lastname>world</lastname>
	</fullname>
	<gender>
		<female>女</female>
		<female>女</female>
		<female>女</female>
		<female>女</female>
		<female>女</female>
	</gender>
	<course>
		<java>java</java>
		<JavaScript>javascript</JavaScript>
		<XML>xml</XML>
	</course>
	<letter>
		<a></a>
		<b></b>
		<c></c>
	</letter>
	<content id=""/>
</person>
